<?php

/**
 * Registers a sidebar in WordPress for React-based widgets
 *
 * Makes a widget area available in WordPress Admin under Appearance > Widgets
 */
function my_theme_register_sidebar()
{
    register_sidebar([
        /** Name shown in the admin panel */
        'name' => 'React Sidebar',

        /** Unique ID used in code to identify the sidebar */
        'id' => 'react-sidebar',

        /** Description shown in the admin panel */
        'description' => 'Sidebar til React-widgets',

        /**
         * HTML Wrapper
         * Wraps each widget in an HTML <div> element
         * WordPress automatically replaces:
         * %1$s -> Widget ID
         * %2$s -> widget CSS classes
         */
        'before_widget' => '<div id="%1$s" class="widget %2$s">',

        /** Close the wrapper after each widget */
        'after_widget' => '</div>',

        /** Wraps the widget title in an HTML <h2> element */
        'before_title' => '<h2 class="widget-title">',

        /** Closes title wrapper */
        'after_title' => '</h2>',
    ]);
}

/**
 * Ensures the React sidebar is recognized by the WordPress Customizer.
 *
 * WordPress Customizer requires widget areas to be rendered in the DOM to detect them
 * To avoid showing the sidebar twice on the frontend, it is wrapped in a hidden <div>.
 *
 * If not in Customizer preview, this function does nothing.
 */
function my_theme_make_sidebar_visible_in_customizer()
{
    /** Only output the sidebar when in the Customizer */
    if (!is_customize_preview()) {
        return;  // Exit early if not in Customizer
    }

    /** Render the sidebar inside a hidden div to make it detectable by the Customizer */
    echo '<div style="display: none;">';
    dynamic_sidebar('react-sidebar');
    echo '</div>';
}

/**
 * Retrieves the HTML content of a sidebar's widgets.
 * 
 * Useful for exposing widget HTML to JS/React via REST API
 * or other dynamic rendering methods.
 * 
 * @param string $sidebar_id The ID of the sidebar to fetch widgets from. Defaults to 'react-sidebar'
 * @return array An array containing the sidebar ID and the HTML of its widgets.
 */
function my_theme_get_sidebar_widgets($sidebar_id = 'react-sidebar')
{
    /** Initialize an empty array to hold the sidebar HTML */
    $widgets_output = [];

    /** Check if the sidebar is active (has widgets) */
    if (is_active_sidebar($sidebar_id)) {
        /** Start output buffering to capture HTML generated by dynamic_sidebar() */
        ob_start();

        /** Render the widgets */
        dynamic_sidebar($sidebar_id);

        /** Get the HTML and clean the buffer */
        $sidebar_html = ob_get_clean();

        /** Stores the sidebar ID and its HTML in the output array */
        $widgets_output[] = [
            'id' => $sidebar_id,
            'content' => $sidebar_html,
        ];
    }

    /** Return the array (empty if sidebar has no widgets) */
    return $widgets_output;
}

/**
 * Registers a custom REST API endpoint for the React sidebar.
 * 
 * Allows JS/React to fetch the sidebar's widget HTML dynamically.
 * 
 * Endpoint:
 *  GET /wp-json/react-widgets/v1/sidebar
 * 
 * Returns:
 * An array containting the sidebar ID and HTML of its widgets
 * as generated by `my_theme_get_sidebar_widgets()`.
 */
function my_theme_register_sidebar_rest_route()
{
    register_rest_route('react-widgets/v1', '/sidebar', [
        'methods' => 'GET',
        'callback' => function () {
            /** Returns the HTML of the 'react-sidebar' widgets */
            return my_theme_get_sidebar_widgets('react-sidebar');
        }
    ]);
}
/**
 * Hook registrations for the React sidebar system.
 * 
 * These connect the custom functions above to WordPress events:
 */

/** Register the React sidebar when WordPress initializes widgets */
add_action('widgets_init', 'my_theme_register_sidebar');

/** Register the REST API route when WordPress initializes the REST API */
add_action('rest_api_init', 'my_theme_register_sidebar_rest_route');

/** Make the sidebar visible in the Customizer by outputting it in a hidden div */
add_action('wp_footer', 'my_theme_make_sidebar_visible_in_customizer');
